.TH FNLFMT 1

.SH NAME
fnlfmt \- a code formatter for Fennel

.SH SYNOPSIS
.B fnlfmt
[\fB--check\fR] |
[\fB--fix\fR] |
[\fB--no-comments\fR] FILENAME...

.SH DESCRIPTION
This manual page documents briefly the
.B fnlfmt
command.

.B fnlfmt
is a code formatter for Fennel code.

.SH OPTIONS

When no command is given, formats the given file and prints the result
to standard out.

.TP
.B \-\-fix
Format the given file and write the result back to the original file.
.TP
.B \-\-check
Fail (exit code 1) if the given file is not currently formatted.
.TP
.B \-\-no\-comments
Strip comments from the file.

.SH DOCUMENTATION

.PP
Formatting is essentially an aesthetic process; any automated attempt
at doing it will necessarily encounter situations where it produces
output that doesn't look as good as it would if a human were making
the decisions. That said, the goal is to at worst emit output which,
if less than ideal, is at least not objectionable. Currently the
indentation decisions it makes are great, but it occasionally puts
newlines in places that a human would not.
.PP
For the most part, fnlfmt follows established lisp conventions when
determining how to format a given piece of code. Key/value tables are
shown with each key/value pair on its own line, unless they are small
enough to all fit on one line. Sequential tables similarly have each
element on their own line unless they fit all on a single line. Tables
with string keys and symbol values will use {: foo : bar}
shorthand notation where possible.
.PP
Calls are formatted differently depending on whether they are calling
a regular function/macro or whether they're calling a special macro
which is known to have a body; in the latter case every element is
given its own line, usually indented 2 spaces in.
.PP
Forms calling match and if are treated differently; if possible it
will attempt to pair off their pattern/condition clauses with the body
on the same line. If that can't fit, it falls back to
one-form-per-line.
.PP
Certain forms which have a body are sometimes allowed to keep their
body on the same line as the call, if the original code has it that
way, provided the body doesn't nest more than two levels and fits in
the line length limit.
.PP
Strings are formatted using :colon-notation where possible, unless
they consist entirely of punctuation.
.PP
Top level forms may or may not have blank lines between them depending
on whether the input code spaces them out. Functions defined inside a
body form get empty lines spacing them out as well.
.PP
Similarly if forms and arrow forms will occasionally be allowed to
be one line if the original code had them as one-liners.
.PP
By design there is no way to configure it; the indentation should be
considered canonical other than bugs or when new features are added to
Fennel itself.

.SH KNOWN ISSUES

.IP \(bu 2
Comments will not be wrapped.
.IP \(bu 2
When using fnlfmt as a library, it may modify the AST argument.
.IP \(bu 2
Function argument lists will be displayed one-per-line if they can't
all fit on one line.

.PP
Some of the issues are inherent to this approach, or at least cannot
be fixed without major changes:

.IP \(bu 2
Numbers are always emitted as decimal; hex notation is not preserved.
.IP \(bu 2
Page breaks and other whitespace will not be preserved.
.IP \(bu 2
Macros that take a body argument but aren't built-in will only be
indented correctly if their name starts with `with-` or
`def`. Functions which use this naming convention will be indented as
if they were macros.

.SH SEE ALSO

.MR fennel 1

.SH COMMUNITY

Report bugs to the main Fennel mailing list at
https://lists.sr.ht/~technomancy/fennel

.SH LICENSE
Copyright © 2019-2024, Released under the MIT/X11 license
